Traceback (most recent call last):
  File "001_dynamic_aperture.py", line 141, in <module>
    Dsigma_wrt_CO_m=0., Ddelta_wrt_CO=0., n_turns=n_turns, device=device)
  File "001_dynamic_aperture.py", line 119, in track_particle_sixtracklib_state
    job = sixtracklib.TrackJob(elements, ps, device=device)
  File "/home/HPC/kparasch/20190715_sixtracklib/packages/sixtracklib/python/sixtracklib/trackjob.py", line 776, in __init__
    max_garbage=num_garbage.value)
  File "/home/HPC/kparasch/20190715_sixtracklib/packages/cobjects/cobjects/cbuffer.py", line 123, in __init__
    self.allocate(max_slots, max_objects, max_pointers, max_garbage)
  File "/home/HPC/kparasch/20190715_sixtracklib/packages/cobjects/cobjects/cbuffer.py", line 154, in allocate
    self._data = np.zeros(size, dtype='uint8')
MemoryError
Done loading!
Tracking time: 280.641342 minutes
